### ISSUE TITLE
"FATAL ERRORS" occurs whenever run original Chris GH definition

### ISSUE THREAD

**Issue by lucianoambrosini** [hansukyang/UWG_Matlab#8] opened 2016-04-23 08:26 UTC
I found a fatal error message after run the original Chris grasshopper definition.
I post the follow files:

screenshot
[https://dl.dropboxusercontent.com/u/28040536/GitHub_ISSUE/UWG/error_batch.JPG](https://dl.dropboxusercontent.com/u/28040536/GitHub_ISSUE/UWG/error_batch.JPG)

The xml file
[https://dl.dropboxusercontent.com/u/28040536/GitHub_ISSUE/UWG/unnamed.xml](https://dl.dropboxusercontent.com/u/28040536/GitHub_ISSUE/UWG/unnamed.xml)

 and GH definition
[https://dl.dropboxusercontent.com/u/28040536/GitHub_ISSUE/UWG/Urban_Weather_Generator_Workflow_v2.gh](https://dl.dropboxusercontent.com/u/28040536/GitHub_ISSUE/UWG/Urban_Weather_Generator_Workflow_v2.gh)

-Luciano

**Comment by hansukyang** [comment] 2016-04-24 18:07
Hi Luciano,

The links included doesn't work - can you check these again?

On the other hand, the 'fatal error' message comes up when a layer is too thin for the simulation to be numerically stable, because the UWG uses a fixed time-step. Some of the roof layers that Chris and a few others that I've seen had either a metal decking (~1mm, and high thermal conductivity) or a membrane (~0.1mm) that were included as roof layers which would make the program unstable. For these cases, the recommendation is to include it as a surface property, since the their thermal mass is light compared to structural layers, or both light and changes temperature fast enough that it's temperature is mostly driven by its albedo/emissivity or whatever it's attached to it.

Let me know if this helps and see if the links can be checked. This is a common problem that we've seen.

Joseph

**Comment by lucianoambrosini** [comment] 2016-04-24 18:16
Thank you Joseph. I repaired my links (sorry my fault), thanks I'll check your helps!

**Comment by hansukyang** [comment] 2016-04-24 18:51
Ok sounds, good, let me know. I just checked the XML file and an example of the problem is the metal decking (there may be more in the file), where you can see that it's very thin and has a high thermal conductivity.

Joseph

<item>ASPHALTMEMBRANE</item><item>METAL ROOF INSULATION</item><item>METAL DECKING</item>
<item>0.02</item><item>0.041123</item><item>45.006</item>
<thickness>[0.01, 0.12602578716560001, 0.0015]</thickness>

**Comment by chriswmackey** [comment] 2016-04-27 01:34
@hansukyang ,
Thanks for looking into this and
@lucianoambrosini ,
Thanks for posting the issue in the first place.

I am realizing that the OpenStudio library contains several materials that are thin enough to make the UWG crash and that I really should have some way of dealing with them.  I can write some code that just excludes any materials from the XML that are below a certain thickness in the Dragonfly interface (and I'll only count their reflectivity/emissivity if they are an outermost layer).  However, I remember the last time that I wrote a workaround for the UWG, Joseph, you fixed the issue in the UWG source code pretty quickly (I'm referring to the running of the UWG for just a part of the year). What do you think is the best course of action to address this situation?  If it seems like a pretty tough bug to solve at the moment, I can easily just put the code in Dragonfly.

Let me know your thoughts,
-Chris

**Comment by hansukyang** [comment] 2016-04-27 12:15
Hi Chris,

The quick fix that I had made in UWG last year was mostly to get it running, and not really a correct fix now that I think about it. It increased the thickness to minimum level that would allow UWG to run (~1cm), but I think excluding them, or only accounting for the reflectivity/emissivity if it's the outer layer should be the correct approach.

I've made quite a lot of updates to UWG so been meaning to get in touch with you before I wrap things up in May. Although it's a bit of duplication, until the new version gets released (end of May), if you can implement that in Dragonfly, it would be helpful for those that use it in the meanwhile.

Thanks, and let me know your thoughts.
Joseph

**Comment by chriswmackey** [comment] 2016-04-29 20:33
@hansukyang ,
Thanks for the clarification.  Following your suggestion, I just put in a check in Dragonfly that excludes any materials with a thickness below 1 cm and just pulls out the albedo/emissivity:
https://github.com/chriswmackey/Dragonfly/commit/c6ea3e9c1c95203d7c7f6fdc30cd195b6f96931c

@lucianoambrosini , you can get your GH file fixed by syncing your Dragonfly components with the Dragonfly github.  I also undated the example file here:
http://hydrashare.github.io/hydra/viewer?owner=chriswmackey&fork=hydra_2&id=Urban_Weather_Generator_Workflow&slide=0&scale=1&offset=0,0

Joesph, we should definitely touch base before you finish up and go over the changes in the May release.  Just send me an email once the craziness of the end of the semester passes.

-Chris

**Closed as completed by chriswmackey** 2016-04-29 20:33 UTC
